void htmlPart(){
  serverIndeks=
  "<HTML>"

"<Head>"
"<title>" "Monitor" "</title>"
"<meta http-equiv=""refresh"" content=""10"">"
"</head>" 
 "<style>"
"body {"
"font-family" "" "comic sans ms;"
"text-align : center;"
"position" ":" "relative;"
"z-index : 1px;"

"background-image: linear-gradient( #ffffff, #98fb98, #2e8bff);"
"}"

".header {"
"margin : 1px"
"background : #003366;"
"border-bottom : 1px solid black;"
"}"

".content {"
"height : 100%;"

"}"

"#tanggal {"
"float : left;"
"height : 100px;"
"width : 47.5%;"
"margin : 2px;"
"margin-left : 2px;"
"background : white;"
"color : black;"
"border-left : 8px solid #872240;"
"font-size: 12px;"
"}"

"#DO {"
"float : right;"
"height : 100px;"
"width : 47.5%;"
"margin : 2px;"
"margin-right:  : 5px;"
"background : white;"
"color : black;"
"border-left : 8px solid #872240;"
"}"

"#ph {"
"float : left;"
"height : 100px;"
"width : 47.5%;"
"margin : 2px;"
"margin-left:  : 5px;"
"background : white;"
"color : black;"
"border-left : 8px solid #482120;"
"}" 

"#EC {"
"float : right;"
"height : 100px;"
"width : 47.5%;"
"margin : 2px;"
"margin-right: r : 5px;"
"background : white;"
"color : black;"
"border-left : 8px solid #546f06;"
"}"

"#suhu {"
"float : left;"
"height : 100px;"
"width : 47.5%;"
"margin : 2px;"
"margin-left:  : 5px;"
"background : white;"
"color : black;"
"border-left : 8px solid #0002a5;"
"}"

"#TDS {"
"float : right;"
"height : 100px;"
"width : 47.5%;"
"margin : 2px;"
"margin-right: r : 5px;"
"background : white;"
"color : black;"
"border-left : 8px solid #546f06;;"
"}"

"#setBacklight {"
"float : center;"
"height : 100px;"
"width : 47.5%;"
"margin : 2px;"

"background : white;"
"color : black;"
"border-left : 8px solid #872240;"
"font-size: 12px;"
"}"

"#footer {"
"margin : 1px;"
"padding : 1px;"
"text-align: center;"
"width: 100%;"
"}"
"</style>"

"<body>"
"<div class=""header"">"
"<h1> Monitor Hidroponik </h1>"
"<p> V 1.7 </p>"
"</div>"

"<div class=""content"">"
"<h2>Parameter</h2>" 

  "<div id=""DO"">"
  "<h2>" "Suhu Dalam GreenHouse" "</h2>"
  "<h3>" +(String)t+ "</h3>"
  "</div>"

  "<div id=""ph"">"
  "<h2>" "Kelembapan Dalam GreenHouse" "</h2>"
  "<h3>" +(String)h+ "</h3>"
  "</div>"

  "<div id=""EC"">"
  "<h2>" "Suhu Luar GreenHouse" "</h2>"
  "<h3>" +(String)t2+ "</h3>"
  "</div>"

  "<div id=""Suhu"">"
  "<h2>" "Kelembapan Luar GreenHouse" "</h2>"
  "<h3>" +(String)h2+ "</h3>"
  "</div>"

  "<div id='setBacklight'>"
  "<h2> Set Backlight </h2>"
  "<h3> <a href='?command1=on'>ON</a>/<a href='?command1=off'>OFF</a> </h3>" 
  "</div>"
  
"</div>"

"<div id=""footer"">"
"<h5> [ ELEKTRONIKA 2019 ] </h5>"
"<h5> [ POLITEKNIK NEGERI BANDUNG ] </h5>"
"</div>"
"</body>"
"</html>" ;
}
